inherit_from: .rubocop_todo.yml

Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 90
AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/**/*'
    - 'bin/*'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'Rakefile'